name: Lint

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Format and Vet
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.22.2'

    - name: Format and Vet Go code
      run: |
        for dir in $(find . -type f -name 'go.mod' | sed 's|/go.mod||'); do
          echo "Formatting and vetting in $dir"
          (cd $dir && go fmt ./... && go vet ./...)
        done